export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS'
export const FETCH_QUESTIONS_FAILED = 'FETCH_QUESTIONS_FAILED'
export const MARK_THE_ANSWER = 'MARK_THE_ANSWER'
export const FETCH_NEXT = "FETCH_NEXT"
export const RETAKE_TEST = "RETAKE_TEST"
export const SET_SELECTED_VALUE = "SET_SELECTED_VALUE"